In [1]:
import numpy as np
from scipy import signal

a = np.arange(25).reshape(5, 5)
b = np.arange(25).reshape(5, 5)
v = np.arange(5)
m = np.array([[1., 2.], [3., 4.]])
n = np.array([[1., 2.], [3., 4.]])
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [2]:
a.ndim

2

In [3]:
a.size

25

In [4]:
a.shape


(5, 5)

In [5]:
(a.shape[1])

5

In [6]:
np.array([[1. ,2. ,3.], [4. ,5. ,6.]])

array([[1., 2., 3.],
       [4., 5., 6.]])

In [7]:
np.block([[1, 2], [3, 4]])

array([[1, 2],
       [3, 4]])

In [8]:
a[-1]

array([20, 21, 22, 23, 24])

In [9]:
	
a[1, 4]

9

In [10]:
	
a[1]

array([5, 6, 7, 8, 9])

In [11]:
	
a[0:5]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [12]:
	
a[-5:]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [13]:
a[0:3, 4:9]

array([[ 4],
       [ 9],
       [14]])

In [14]:
a[np.ix_([1, 3, 4], [0, 2])]

array([[ 5,  7],
       [15, 17],
       [20, 22]])

In [15]:
a[2:21:2,:]

array([[10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

In [16]:
a[ ::2,:]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

In [17]:
a[::-1,:]

array([[20, 21, 22, 23, 24],
       [15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4]])

In [18]:
a[np.r_[:len(a),0]]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [ 0,  1,  2,  3,  4]])

In [19]:
a.transpose()

array([[ 0,  5, 10, 15, 20],
       [ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24]])

In [20]:
a.conj().transpose()

array([[ 0,  5, 10, 15, 20],
       [ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24]])

In [21]:
a @ b

array([[ 150,  160,  170,  180,  190],
       [ 400,  435,  470,  505,  540],
       [ 650,  710,  770,  830,  890],
       [ 900,  985, 1070, 1155, 1240],
       [1150, 1260, 1370, 1480, 1590]])

In [22]:
a * b

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]])

In [23]:
print(a / b)

[[nan  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]]


<ipython-input-23-d6b2d2e1f031>:1: RuntimeWarning: invalid value encountered in true_divide
  print(a / b)


In [24]:
a ** 3

array([[    0,     1,     8,    27,    64],
       [  125,   216,   343,   512,   729],
       [ 1000,  1331,  1728,  2197,  2744],
       [ 3375,  4096,  4913,  5832,  6859],
       [ 8000,  9261, 10648, 12167, 13824]])

In [25]:
(a > 0.5)

array([[False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [26]:
np.nonzero(a > 0.5)

(array([0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4,
        4, 4]),
 array([1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2,
        3, 4]))

In [27]:
a[:,np.nonzero(v > 0.5)[0]]

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14],
       [16, 17, 18, 19],
       [21, 22, 23, 24]])

In [28]:
a[:, v.T > 0.5]

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14],
       [16, 17, 18, 19],
       [21, 22, 23, 24]])

In [29]:
a[a < 0.5] = 0
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [30]:
a * (a > 0.5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [31]:
v[:] = 3
v

array([3, 3, 3, 3, 3])

In [32]:
b = a.copy()
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [33]:
b = a[1, :].copy()
b

array([5, 6, 7, 8, 9])

In [34]:
b = a.flatten()
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [35]:
np.arange(1., 11.)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [36]:
np.arange(10.)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [37]:
np.arange(1.,11.)[:, np.newaxis]

array([[ 1.],
       [ 2.],
       [ 3.],
       [ 4.],
       [ 5.],
       [ 6.],
       [ 7.],
       [ 8.],
       [ 9.],
       [10.]])

In [38]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [39]:
np.zeros((3, 4, 5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [40]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [41]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [42]:
np.diag(a)

array([ 0,  6, 12, 18, 24])

In [43]:
np.diag(v, 0)

array([[3, 0, 0, 0, 0],
       [0, 3, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 3]])

In [44]:
np.random.rand(3, 4)

array([[0.40540768, 0.0663157 , 0.56876454, 0.20224389],
       [0.42118894, 0.79592746, 0.7783248 , 0.61219599],
       [0.64075211, 0.49943684, 0.84190663, 0.66826499]])

In [45]:
np.linspace(1,3,4)

array([1.        , 1.66666667, 2.33333333, 3.        ])

In [46]:
np.mgrid[0:9.,0:6.]

array([[[0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1.],
        [2., 2., 2., 2., 2., 2.],
        [3., 3., 3., 3., 3., 3.],
        [4., 4., 4., 4., 4., 4.],
        [5., 5., 5., 5., 5., 5.],
        [6., 6., 6., 6., 6., 6.],
        [7., 7., 7., 7., 7., 7.],
        [8., 8., 8., 8., 8., 8.]],

       [[0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.]]])

In [47]:
np.ix_(np.r_[0:9.],np.r_[0:6.])

(array([[0.],
        [1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.]]),
 array([[0., 1., 2., 3., 4., 5.]]))

In [48]:
np.meshgrid([1,2,4],[2,4,5])

[array([[1, 2, 4],
        [1, 2, 4],
        [1, 2, 4]]),
 array([[2, 2, 2],
        [4, 4, 4],
        [5, 5, 5]])]

In [49]:
np.ix_([1,2,4],[2,4,5])

(array([[1],
        [2],
        [4]]),
 array([[2, 4, 5]]))

In [50]:
np.tile(a, (3, 4))

array([[ 0,  1,  2,  3,  4,  0,  1,  2,  3,  4,  0,  1,  2,  3,  4,  0,
         1,  2,  3,  4],
       [ 5,  6,  7,  8,  9,  5,  6,  7,  8,  9,  5,  6,  7,  8,  9,  5,
         6,  7,  8,  9],
       [10, 11, 12, 13, 14, 10, 11, 12, 13, 14, 10, 11, 12, 13, 14, 10,
        11, 12, 13, 14],
       [15, 16, 17, 18, 19, 15, 16, 17, 18, 19, 15, 16, 17, 18, 19, 15,
        16, 17, 18, 19],
       [20, 21, 22, 23, 24, 20, 21, 22, 23, 24, 20, 21, 22, 23, 24, 20,
        21, 22, 23, 24],
       [ 0,  1,  2,  3,  4,  0,  1,  2,  3,  4,  0,  1,  2,  3,  4,  0,
         1,  2,  3,  4],
       [ 5,  6,  7,  8,  9,  5,  6,  7,  8,  9,  5,  6,  7,  8,  9,  5,
         6,  7,  8,  9],
       [10, 11, 12, 13, 14, 10, 11, 12, 13, 14, 10, 11, 12, 13, 14, 10,
        11, 12, 13, 14],
       [15, 16, 17, 18, 19, 15, 16, 17, 18, 19, 15, 16, 17, 18, 19, 15,
        16, 17, 18, 19],
       [20, 21, 22, 23, 24, 20, 21, 22, 23, 24, 20, 21, 22, 23, 24, 20,
        21, 22, 23, 24],
       [ 0,  1,  2,  3,  4,  0

In [51]:
a = np.arange(25).reshape(5, 5)
b = np.arange(25).reshape(5, 5)
np.concatenate((a,b),1)

array([[ 0,  1,  2,  3,  4,  0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 20, 21, 22, 23, 24]])

In [52]:
np.concatenate((a,b))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [53]:
a.max()

24

In [54]:
a.max(0)

array([20, 21, 22, 23, 24])

In [55]:
a.max(1)

array([ 4,  9, 14, 19, 24])

In [56]:
np.maximum(a, b)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [57]:
np.sqrt(v @ v)

6.708203932499369

In [58]:
np.logical_and(a,b)

array([[False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [59]:
np.logical_or(a,b)

array([[False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [60]:
a & b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [61]:
a | b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [62]:
np.linalg.inv(m)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [63]:
np.linalg.pinv(m)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [64]:
np.linalg.matrix_rank(m)

2

In [65]:
np.linalg.solve(m, n)

array([[1.00000000e+00, 0.00000000e+00],
       [8.32667268e-17, 1.00000000e+00]])

In [66]:
np.linalg.svd(a)

(array([[-0.06767881, -0.77163436,  0.63224391,  0.00167672,  0.01627349],
        [-0.22699517, -0.49847085, -0.64277772,  0.40439987,  0.3511375 ],
        [-0.38631153, -0.22530735, -0.29501495, -0.26831145, -0.80060923],
        [-0.54562789,  0.04785615, -0.01061257, -0.68328362,  0.482712  ],
        [-0.70494424,  0.32101965,  0.31616133,  0.54551847, -0.04951376]]),
 array([6.99085940e+01, 3.57609824e+00, 5.72246903e-15, 2.09124342e-16,
        6.08024818e-17]),
 array([[-0.39024378, -0.41787354, -0.4455033 , -0.47313306, -0.50076282],
        [ 0.66911119,  0.35409279,  0.03907438, -0.27594403, -0.59096243],
        [ 0.37572717,  0.02608843, -0.58890396, -0.40336606,  0.59045442],
        [-0.38884163,  0.47076134,  0.40132636, -0.65957023,  0.17632416],
        [-0.32807206,  0.69116073, -0.54048985,  0.31978575, -0.14238457]]))

In [67]:
c = np.array([[1,-2j],[2j,5]])
np.linalg.cholesky(c)

array([[1.+0.j, 0.+0.j],
       [0.+2.j, 1.+0.j]])

In [68]:
np.linalg.eig(a)

(array([ 6.39116499e+01, -3.91164992e+00,  3.19626490e-15, -1.64396509e-15,
         8.90756696e-17]),
 array([[-0.0851802 ,  0.67779864,  0.06945307, -0.39148436, -0.10985832],
        [-0.23825372,  0.36348873,  0.44032228,  0.290592  , -0.03338055],
        [-0.39132723,  0.04917881, -0.57200489,  0.01857127,  0.63352165],
        [-0.54440074, -0.2651311 , -0.45476933,  0.6570189 , -0.72746836],
        [-0.69747425, -0.57944101,  0.51699887, -0.5746978 ,  0.23718558]]))

In [69]:
np.linalg.qr(a)

(array([[ 0.00000000e+00, -7.74596669e-01,  6.31373603e-01,
         -3.43074273e-02, -1.37975813e-02],
        [-1.82574186e-01, -5.16397779e-01, -6.00582802e-01,
          4.65904120e-01,  3.49619292e-01],
        [-3.65148372e-01, -2.58198890e-01, -3.50181388e-01,
         -3.07929335e-01, -7.63251282e-01],
        [-5.47722558e-01, -3.64316988e-17, -2.33832327e-02,
         -6.44623979e-01,  5.32835012e-01],
        [-7.30296743e-01,  2.58198890e-01,  3.42773819e-01,
          5.20956622e-01, -1.05405441e-01]]),
 array([[-2.73861279e+01, -2.92118697e+01, -3.10376116e+01,
         -3.28633535e+01, -3.46890953e+01],
        [ 0.00000000e+00, -1.29099445e+00, -2.58198890e+00,
         -3.87298335e+00, -5.16397779e+00],
        [ 0.00000000e+00,  0.00000000e+00,  2.61397004e-15,
          5.09829244e-15,  8.73506122e-15],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          1.86243709e-16, -1.70413110e-16],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
  

In [70]:
np.fft.fft(v)

array([15.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j])

In [71]:
np.fft.ifft(v)

array([3.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j])

In [72]:
np.sort(a)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [73]:
np.sort(a, axis = 1)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [74]:
I = np.argsort(a[:, 0])
I

array([0, 1, 2, 3, 4])

In [75]:
a[I,:]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [76]:
x = np.linspace(0, 10, 20, endpoint=False)
y = np.cos(-x**2/6.0)
f = signal.resample(y, 100)
signal.resample(y, 100)



array([ 1.        ,  1.23283311,  1.31727019,  1.27302765,  1.14740269,
        0.99913207,  0.88078847,  0.82497964,  0.83806509,  0.90249922,
        0.98614323,  1.05486   ,  1.08402435,  1.06536954,  1.00747904,
        0.93050762,  0.85758366,  0.80620995,  0.78263328,  0.78081837,
        0.78588726,  0.78033048,  0.75048699,  0.69094819,  0.60552319,
        0.50478221,  0.40143727,  0.30548407,  0.22092394,  0.14511765,
        0.0707372 , -0.01068719, -0.10512733, -0.21370903, -0.33240564,
       -0.45366208, -0.56910426, -0.67215691, -0.75955883, -0.83131707,
       -0.88932657, -0.93540864, -0.9696874 , -0.98998822, -0.9924354 ,
       -0.97288395, -0.92847886, -0.85863231, -0.76502853, -0.65074937,
       -0.51903563, -0.37236513, -0.21236454, -0.04065068,  0.13978552,
        0.3233596 ,  0.50154373,  0.66375109,  0.79927642,  0.89960584,
        0.96017029,  0.98077748,  0.96447814,  0.91530208,  0.8358487 ,
        0.7258814 ,  0.58274561,  0.40370101,  0.18940426, -0.05

In [77]:
np.unique(a)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [78]:
a.squeeze()

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])